server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh8001 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由


        - id: payment_routh8002 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/create         # 断言，路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
      #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

